config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end
 

app/models/user.rb
# Implicit Attr
# email: string
# password_digest: string
#
# has_secure_password gives us the following
# Virtual Attr
# password: string
# password_confirmation: string

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be logged in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def edit

    end

    def update
        if Current.user.update(password_params)
            puts password_params
            redirect_to root_path, notice: "Password was successfully updated"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: 'User was successfully created'
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Login successful. Welcome to Chikin..."
        else
            flash.now[:alert] = "Invalid email or password. You know why I'm not telling you which..."
            render :new
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About the app</h1>

<div class="container">
    <div class="block" id="purpose">
        <h3>Purpose</h3>
        <p>
            Chikin fills the gap between twitter and LinkedIn. Chikin is not intended for annonimity and unlimited free speech.
            Chikin is simply intended to be a more focused tool for social-based learning and development amongst the tech community.
        </p>
    </div>

    <div class="block" id="posts">
        <h3>Posts</h3>

        <p>Chickin posts are broken up into 2 categories.</p>
        <li><strong>Nuggets:</strong> These are bits of wisdom (i.e. TIL..., Quick tips, etc.).</li>
        <li><strong>Eggs:</strong> These are where we can share our own mistakes that others can learn from as we have.</li>
    </div>
    <div class="block" id="chikinocracy">
        <h3>Chikinocracy</h3>

        <p>Chikin's primary differentiator is that the site's moderation is entirely democratic. </p>
        <ul>
            <li>First, Chikin is invite only and users are attributed to those that invited them.</li>
            <li>Second, Chikin users will be able to open a vote for removal on any post or user. This will open a discussion specific to this event where the user initiating the vote can make their case and other users can have open dialog on the matter. Then the community will have 24 hours to decide whether that content or user should be removed using a simple yes/no vote.</li>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Chikin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- / BOOTSTRAP -->

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
    <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to Chikin</h1>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Chikin", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>